output_dir: ${OUTPUT_DIR}

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: ${INPUT_DIR}
    n_train: 32768
    n_valid: 4096
    real_weight: 3. #5.0   # 0.5 / 0.1
    batch_size: 2
    n_workers: 0

model:
    name: agnn
    input_dim: 3
    hidden_dim: 64
    layer_norm: true
    n_graph_iters: 8
    loss_func: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    learning_rate: 0.0001
    lr_scaling: sqrt
    lr_warmup_epochs: 5
    lr_decay_schedule:
        - {start_epoch: 10, end_epoch: 20, factor: 0.1}
        - {start_epoch: 20, end_epoch: 30, factor: 0.01}

training:
    n_epochs: 40
#    n_epochs: 96
